CaptchaException: -wrapper to forward more information (eg skiprequest or blacklistentry) -extends PluginException to provide plugin compatibility CaptchaBlackList: modified to return blocking BlackListEntry PluginForHost: -updated to use new CaptchaException -updated some Exception handling PluginForDecrypt: -updated to use new CaptchaException -updated some Exception handling